// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCiaHZ66bjxPuVoypoGhc80P_4PnCK_04',
    appId: '1:302517447687:web:ce53c855657d781f23cea2',
    messagingSenderId: '302517447687',
    projectId: 'breeds-app-87309',
    authDomain: 'breeds-app-87309.firebaseapp.com',
    storageBucket: 'breeds-app-87309.appspot.com',
    measurementId: 'G-22F1MS5SCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51rhmZUm9fK8qJle8o45Msm-jUsgLIWM',
    appId: '1:302517447687:android:64bc89a935cef3fb23cea2',
    messagingSenderId: '302517447687',
    projectId: 'breeds-app-87309',
    storageBucket: 'breeds-app-87309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJLZ_5Wky0B0VHqwnuCYkUNAH2dYEEb00',
    appId: '1:302517447687:ios:001f7c38a5dcdef823cea2',
    messagingSenderId: '302517447687',
    projectId: 'breeds-app-87309',
    storageBucket: 'breeds-app-87309.appspot.com',
    iosBundleId: 'com.example.parcial1Pineiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJLZ_5Wky0B0VHqwnuCYkUNAH2dYEEb00',
    appId: '1:302517447687:ios:001f7c38a5dcdef823cea2',
    messagingSenderId: '302517447687',
    projectId: 'breeds-app-87309',
    storageBucket: 'breeds-app-87309.appspot.com',
    iosBundleId: 'com.example.parcial1Pineiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCiaHZ66bjxPuVoypoGhc80P_4PnCK_04',
    appId: '1:302517447687:web:e7b8fe03e8d38ec323cea2',
    messagingSenderId: '302517447687',
    projectId: 'breeds-app-87309',
    authDomain: 'breeds-app-87309.firebaseapp.com',
    storageBucket: 'breeds-app-87309.appspot.com',
    measurementId: 'G-093LW717BT',
  );
}
