name: parcial_1_pineiro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animate_do: ^3.3.4
  cloud_firestore: ^5.4.4
  encrypt_shared_preferences: ^0.8.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_picker_plus: ^1.3.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  html_unescape: ^2.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1

dev_dependencies:
  build_runner: ^2.4.12
  floor_generator: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/breeds.json
    - assets/users.json
    - assets/Dog_Breeds_app_logo.png
